import type { HomepageExample } from './homepageExamples'

export type HomepageExampleItemVariant = 'original64' | 'outline32'
export type HomepageExampleItemSubject = { zh: string; en: string }

const itemSlotCount = 8

export const homepageExampleItemSubjects: Record<string, readonly HomepageExampleItemSubject[]> = {
  "01_wuxia": [
    { zh: "水墨长剑", en: "ink-wash sword" },
    { zh: "竹笛", en: "bamboo flute" },
    { zh: "玉佩", en: "jade pendant" },
    { zh: "丝绢卷轴", en: "silk scroll" },
    { zh: "铁扇", en: "iron fan" },
    { zh: "铜钱", en: "copper coins" },
    { zh: "茶具", en: "tea set" },
    { zh: "毛笔", en: "Calligraphy Brush" },
  ],
  "02_xianxia": [
    { zh: "发光灵石", en: "glowing spirit stones" },
    { zh: "玉制丹瓶", en: "jade pill bottles" },
    { zh: "飞剑", en: "flying sword" },
    { zh: "道符", en: "taoist talismans" },
    { zh: "八卦镜", en: "bagua mirror" },
    { zh: "仙袍", en: "celestial robe" },
    { zh: "灵葫芦", en: "Spirit Gourd" },
    { zh: "炼丹炉", en: "Alchemy Cauldron" },
  ],
  "03_xuanhuan": [
    { zh: "燃焰天剑", en: "flaming heavenly sword" },
    { zh: "龙鳞甲", en: "dragon scale armor" },
    { zh: "凤凰羽", en: "phoenix feather" },
    { zh: "炼丹炉", en: "pill cauldron" },
    { zh: "魂珠", en: "soul orb" },
    { zh: "上古典籍", en: "ancient tome" },
    { zh: "阴阳令牌", en: "Yin-Yang Talisman" },
    { zh: "符文手镯", en: "Rune Bracelet" },
  ],
  "04_palace": [
    { zh: "凤钗", en: "phoenix hairpin" },
    { zh: "玉玺", en: "jade seal" },
    { zh: "丝绸团扇", en: "silk fan" },
    { zh: "瓷瓶", en: "porcelain vase" },
    { zh: "香炉", en: "incense burner" },
    { zh: "刺绣华服", en: "embroidered robe" },
    { zh: "珠宝匣", en: "Jewelry Box" },
    { zh: "如意权杖", en: "Ruyi Scepter" },
  ],
  "05_myth": [
    { zh: "九尾狐护符", en: "nine-tailed fox charm" },
    { zh: "玉兔", en: "jade rabbit" },
    { zh: "青铜面具", en: "bronze mask" },
    { zh: "神秘葫芦", en: "mystic gourd" },
    { zh: "仙桃", en: "peach of immortality" },
    { zh: "鬼灯笼", en: "ghost lantern" },
    { zh: "神珠", en: "Divine Orb" },
    { zh: "羽饰法器", en: "Feather Relic" },
  ],
  "06_sanguo": [
    { zh: "青龙偃月刀", en: "guandao halberd" },
    { zh: "武将头盔", en: "general helmet" },
    { zh: "战鼓", en: "war drum" },
    { zh: "兵法卷轴", en: "strategy scroll" },
    { zh: "将令印", en: "command seal" },
    { zh: "酒壶", en: "wine jug" },
    { zh: "羽扇", en: "Feather Fan" },
    { zh: "短剑", en: "Short Sword" },
  ],
  "07_wafu": [
    { zh: "武士刀", en: "katana" },
    { zh: "鬼面具", en: "oni mask" },
    { zh: "纸灯笼", en: "paper lantern" },
    { zh: "折扇", en: "folding fan" },
    { zh: "清酒瓶", en: "sake bottle" },
    { zh: "榻榻米", en: "tatami" },
    { zh: "樱花枝", en: "sakura branch" },
    { zh: "御守", en: "Omamori Charm" },
  ],
  "08_urbanxian": [
    { zh: "道法应用手机", en: "smartphone with taoist app" },
    { zh: "发光玉镯", en: "glowing jade bracelet" },
    { zh: "符咒卡", en: "talisman card" },
    { zh: "公文包剑", en: "briefcase sword" },
    { zh: "玉佩", en: "Jade Pendant" },
    { zh: "灵药瓶", en: "Elixir Vial" },
    { zh: "符文耳机", en: "Rune Headphones" },
    { zh: "罗盘", en: "Compass" },
  ],
  "09_highfantasy": [
    { zh: "附魔长剑", en: "enchanted longsword" },
    { zh: "法术书", en: "spellbook" },
    { zh: "法力药水", en: "mana potion" },
    { zh: "水晶法杖", en: "crystal staff" },
    { zh: "精灵弓", en: "elven bow" },
    { zh: "矮人战锤", en: "dwarven hammer" },
    { zh: "龙纹盾", en: "dragon shield" },
    { zh: "翡翠项链", en: "Emerald Necklace" },
  ],
  "10_lowfantasy": [
    { zh: "磨损铁剑", en: "worn iron sword" },
    { zh: "皮革日志", en: "leather journal" },
    { zh: "生锈匕首", en: "rusty dagger" },
    { zh: "面包奶酪", en: "bread cheese" },
    { zh: "锡杯", en: "tin cup" },
    { zh: "粗糙地图", en: "crude map" },
    { zh: "油灯", en: "oil lantern" },
    { zh: "提灯", en: "Hand Lantern" },
  ],
  "11_swordsorcery": [
    { zh: "蛮族阔剑", en: "barbarian broadsword" },
    { zh: "骨制护符", en: "bone amulet" },
    { zh: "骷髅杯", en: "skull cup" },
    { zh: "部落斧", en: "tribal axe" },
    { zh: "毛皮斗篷", en: "fur cloak" },
    { zh: "粗糙神像", en: "crude idol" },
    { zh: "铜剑", en: "Bronze Sword" },
    { zh: "骷髅图腾", en: "Skull Totem" },
  ],
  "12_darkfantasy": [
    { zh: "诅咒巨剑", en: "cursed greatsword" },
    { zh: "染血圣杯", en: "bloody chalice" },
    { zh: "腐烂魔典", en: "rotting tome" },
    { zh: "失色王冠", en: "tarnished crown" },
    { zh: "黑蜡烛", en: "black candle" },
    { zh: "瘟疫面具", en: "plague mask" },
    { zh: "黑香炉", en: "Dark Censer" },
    { zh: "铁牢笼", en: "Iron Cage" },
  ],
  "13_medieval": [
    { zh: "骑士佩剑", en: "arming sword" },
    { zh: "锁子甲", en: "chainmail" },
    { zh: "木盾", en: "wooden shield" },
    { zh: "皮靴", en: "leather boots" },
    { zh: "铁盔", en: "iron helm" },
    { zh: "面包", en: "bread" },
    { zh: "木桶", en: "barrel" },
    { zh: "锁子头巾", en: "Chain Hood" },
  ],
  "14_fairytale": [
    { zh: "玻璃鞋", en: "glass slipper" },
    { zh: "魔豆种子", en: "magic beanstalk seed" },
    { zh: "小红帽斗篷", en: "red riding hood cape" },
    { zh: "毒苹果", en: "poisoned apple" },
    { zh: "仙女魔杖", en: "fairy wand" },
    { zh: "姜饼", en: "gingerbread" },
    { zh: "皇冠", en: "Crown" },
    { zh: "魔镜", en: "Magic Mirror" },
  ],
  "15_norse": [
    { zh: "雷神之锤", en: "Mjolnir hammer" },
    { zh: "卢恩石", en: "rune stone" },
    { zh: "饮酒角杯", en: "drinking horn" },
    { zh: "维京战斧", en: "viking axe" },
    { zh: "狼皮", en: "wolf pelt" },
    { zh: "金臂环", en: "gold arm ring" },
    { zh: "世界树枝", en: "yggdrasil branch" },
    { zh: "圆盾", en: "Round Shield" },
  ],
  "16_celtic": [
    { zh: "扭曲木杖", en: "twisted wooden staff" },
    { zh: "槲寄生", en: "mistletoe" },
    { zh: "凯尔特结护符", en: "celtic knot amulet" },
    { zh: "柳条篮", en: "wicker basket" },
    { zh: "欧甘石", en: "ogham stones" },
    { zh: "坩埚", en: "cauldron" },
    { zh: "镰刀", en: "Sickle" },
    { zh: "橡叶护符", en: "Oak Leaf Amulet" },
  ],
  "17_greek": [
    { zh: "月桂花冠", en: "laurel wreath" },
    { zh: "黄金三叉戟", en: "golden trident" },
    { zh: "橄榄枝", en: "olive branch" },
    { zh: "大理石半身像", en: "marble bust" },
    { zh: "双耳酒罐", en: "wine amphora" },
    { zh: "青铜盾", en: "bronze shield" },
    { zh: "斯巴达头盔", en: "spartan helmet" },
    { zh: "贝壳徽章", en: "Shell Emblem" },
  ],
  "18_egyptian": [
    { zh: "安卡钥匙", en: "ankh key" },
    { zh: "圣甲虫护符", en: "scarab amulet" },
    { zh: "卡诺匹斯罐", en: "canopic jar" },
    { zh: "黄金面具", en: "golden mask" },
    { zh: "法老王冠", en: "pharaoh crown" },
    { zh: "莎草纸卷轴", en: "papyrus scroll" },
    { zh: "瓦斯权杖", en: "was scepter" },
    { zh: "圣甲虫护符", en: "Scarab Amulet" },
  ],
  "19_hardscifi": [
    { zh: "等离子步枪", en: "plasma rifle" },
    { zh: "磁力靴", en: "magnetic boots" },
    { zh: "数据芯片", en: "data chip" },
    { zh: "氧气罐", en: "oxygen tank" },
    { zh: "舱外宇航头盔", en: "EVA helmet" },
    { zh: "聚变电池", en: "fusion cell" },
    { zh: "扫描器", en: "Scanner" },
    { zh: "能量核心", en: "Energy Core" },
  ],
  "20_spaceopera": [
    { zh: "激光剑", en: "laser sword" },
    { zh: "星舰钥匙", en: "starship key" },
    { zh: "外星遗物", en: "alien artifact" },
    { zh: "宇宙宝石", en: "cosmic gem" },
    { zh: "指挥官徽章", en: "commander badge" },
    { zh: "等离子爆能枪", en: "plasma blaster" },
    { zh: "星图芯片", en: "Star Map Chip" },
    { zh: "能量电池", en: "Power Cell" },
  ],
  "21_cyberpunk": [
    { zh: "赛博武士刀", en: "cyber katana" },
    { zh: "神经植入芯片", en: "neural implant chip" },
    { zh: "全息手机", en: "holo-phone" },
    { zh: "能量饮料", en: "energy drink" },
    { zh: "赛博义肢", en: "cyber arm" },
    { zh: "数据碎片", en: "data shard" },
    { zh: "数据护目镜", en: "Data Goggles" },
    { zh: "霓虹电池", en: "Neon Battery" },
  ],
  "22_steampunk": [
    { zh: "黄铜护目镜", en: "brass goggles" },
    { zh: "齿轮机构", en: "gear mechanism" },
    { zh: "怀表", en: "pocket watch" },
    { zh: "蒸汽手枪", en: "steam pistol" },
    { zh: "压力表", en: "pressure gauge" },
    { zh: "皮革高礼帽", en: "leather top hat" },
    { zh: "机械手套", en: "Clockwork Gauntlet" },
    { zh: "蒸汽背包", en: "Steam Backpack" },
  ],
  "23_dieselpunk": [
    { zh: "汤普森冲锋枪", en: "tommy gun" },
    { zh: "防毒面具", en: "gas mask" },
    { zh: "飞艇钥匙", en: "zeppelin key" },
    { zh: "皮革飞行帽", en: "leather aviator cap" },
    { zh: "宣传海报", en: "propaganda poster" },
    { zh: "燃油罐", en: "fuel canister" },
    { zh: "飞行护目镜", en: "Aviator Goggles" },
    { zh: "打火机", en: "Lighter" },
  ],
  "24_biopunk": [
    { zh: "脉动血肉剑", en: "pulsating flesh sword" },
    { zh: "DNA 试管", en: "DNA vial" },
    { zh: "有机植入体", en: "organic implant" },
    { zh: "生化注射器", en: "bio-syringe" },
    { zh: "眼球罐", en: "eyeball jar" },
    { zh: "孢子手雷", en: "Spore Grenade" },
    { zh: "生物芯片", en: "Biochip" },
    { zh: "注射器", en: "Injector" },
  ],
  "25_atompunk": [
    { zh: "射线枪", en: "ray gun" },
    { zh: "真空管收音机", en: "vacuum tube radio" },
    { zh: "原子汽水瓶", en: "atomic soda bottle" },
    { zh: "五十年代午餐盒", en: "50s lunchbox" },
    { zh: "盖革计数器", en: "geiger counter" },
    { zh: "铬合金机器人", en: "chrome robot" },
    { zh: "原子台灯", en: "Atomic Lamp" },
    { zh: "核能电池", en: "Nuclear Battery" },
  ],
  "26_solarpunk": [
    { zh: "藤蔓太阳能板", en: "vine-wrapped solar panel" },
    { zh: "种子袋", en: "seed pouch" },
    { zh: "净水瓶", en: "clean water flask" },
    { zh: "竹制自行车", en: "bamboo bicycle" },
    { zh: "生态手机", en: "eco-phone" },
    { zh: "太阳能灯", en: "Solar Lantern" },
    { zh: "园艺工具包", en: "Gardening Kit" },
    { zh: "发条电池", en: "Windup Battery" },
  ],
  "27_wasteland": [
    { zh: "生锈管钳", en: "rusty pipe wrench" },
    { zh: "废料护甲", en: "scrap armor" },
    { zh: "污染水瓶", en: "contaminated water bottle" },
    { zh: "防毒面具", en: "gas mask" },
    { zh: "临时步枪", en: "makeshift rifle" },
    { zh: "抗辐射药片", en: "radiation pill" },
    { zh: "辐射计", en: "Geiger Counter" },
    { zh: "生存匕首", en: "Survival Knife" },
  ],
  "28_nearfuture": [
    { zh: "智能眼镜", en: "smart glasses" },
    { zh: "无人机", en: "drone" },
    { zh: "加密 U 盘", en: "encrypted USB" },
    { zh: "战术夹克", en: "tactical jacket" },
    { zh: "黑客笔记本", en: "hacking laptop" },
    { zh: "品牌咖啡杯", en: "branded coffee cup" },
    { zh: "电子芯片", en: "Circuit Chip" },
    { zh: "信号路由器", en: "Signal Router" },
  ],
  "29_cthulhu": [
    { zh: "禁忌魔典", en: "forbidden tome" },
    { zh: "触手神像", en: "tentacle idol" },
    { zh: "仪式匕首", en: "ritual dagger" },
    { zh: "旧左轮手枪", en: "old revolver" },
    { zh: "理智药片", en: "sanity pill" },
    { zh: "诡异遗物", en: "strange artifact" },
    { zh: "邪眼钥匙", en: "Eldritch Key" },
    { zh: "邪能提灯", en: "Eldritch Lantern" },
  ],
  "30_gothic": [
    { zh: "银十字架", en: "silver cross" },
    { zh: "圣水小瓶", en: "holy water vial" },
    { zh: "木桩", en: "wooden stake" },
    { zh: "烛台", en: "candelabra" },
    { zh: "染血圣杯", en: "bloody chalice" },
    { zh: "棺材钥匙", en: "coffin key" },
    { zh: "玫瑰念珠", en: "Rose Rosary" },
    { zh: "骷髅魔典", en: "Skull Grimoire" },
  ],
  "31_zombie": [
    { zh: "染血霰弹枪", en: "blood-stained shotgun" },
    { zh: "草药包", en: "herb kit" },
    { zh: "绷带", en: "bandage" },
    { zh: "撬棍", en: "crowbar" },
    { zh: "罐头食品", en: "canned food" },
    { zh: "应急信号棒", en: "emergency flare" },
    { zh: "弹药箱", en: "Ammo Box" },
    { zh: "血刃", en: "Bloody Knife" },
  ],
  "32_psycho": [
    { zh: "锈蚀小刀", en: "rusted knife" },
    { zh: "药瓶", en: "pill bottle" },
    { zh: "破镜碎片", en: "broken mirror shard" },
    { zh: "旧照片", en: "old photograph" },
    { zh: "闪烁手电筒", en: "flickering flashlight" },
    { zh: "旧钥匙", en: "Old Key" },
    { zh: "怀表", en: "Pocket Watch" },
    { zh: "诅咒玩偶", en: "Cursed Doll" },
  ],
  "33_urbanlegend": [
    { zh: "诅咒娃娃", en: "cursed doll" },
    { zh: "红包", en: "red envelope" },
    { zh: "闹鬼手机", en: "haunted phone" },
    { zh: "便利店小票", en: "convenience store receipt" },
    { zh: "御札护符", en: "ofuda charm" },
    { zh: "手镜", en: "Hand Mirror" },
    { zh: "磁带", en: "Cassette Tape" },
    { zh: "护符钥匙", en: "Charm Keys" },
  ],
  "34_folkhorror": [
    { zh: "稻草人偶", en: "straw doll" },
    { zh: "仪式小刀", en: "ritual knife" },
    { zh: "旧香", en: "old incense" },
    { zh: "泛黄符纸", en: "yellowed talisman" },
    { zh: "陶土神像", en: "clay idol" },
    { zh: "裹尸布", en: "burial shroud" },
    { zh: "祭祀碗", en: "Ritual Bowl" },
    { zh: "草绳护符", en: "Straw Charm" },
  ],
  "35_analoghorror": [
    { zh: "录像带", en: "VHS tape" },
    { zh: "显像管遥控器", en: "CRT remote" },
    { zh: "广播徽章", en: "broadcast badge" },
    { zh: "雪花噪点照片", en: "static photo" },
    { zh: "紧急广播卡", en: "emergency broadcast card" },
    { zh: "雪花电视", en: "Static TV" },
    { zh: "对讲喇叭", en: "Intercom Speaker" },
    { zh: "监控摄像头", en: "Security Camera" },
  ],
  "36_bodyhorror": [
    { zh: "脉动血肉武器", en: "pulsing flesh weapon" },
    { zh: "骨刺", en: "bone spike" },
    { zh: "变异器官", en: "mutated organ" },
    { zh: "手术锯", en: "surgical saw" },
    { zh: "变异药瓶", en: "mutation vial" },
    { zh: "肋骨护甲", en: "Rib Armor" },
    { zh: "肉钩", en: "Flesh Hook" },
    { zh: "眼球怪", en: "Eyeball Mutant" },
  ],
  "37_modern": [
    { zh: "智能手机", en: "smartphone" },
    { zh: "咖啡杯", en: "coffee cup" },
    { zh: "车钥匙", en: "car keys" },
    { zh: "皮钱包", en: "leather wallet" },
    { zh: "无线耳机", en: "earbuds" },
    { zh: "能量棒", en: "energy bar" },
    { zh: "交通卡", en: "Transit Card" },
    { zh: "充电宝", en: "Power Bank" },
  ],
  "38_school": [
    { zh: "课本", en: "textbook" },
    { zh: "铅笔盒", en: "pencil case" },
    { zh: "便当盒", en: "bento box" },
    { zh: "运动哨", en: "sports whistle" },
    { zh: "学生证", en: "student ID" },
    { zh: "情书", en: "love letter" },
    { zh: "樱花笔记本", en: "Sakura Notebook" },
    { zh: "书包", en: "School Backpack" },
  ],
  "39_gangster": [
    { zh: "纹身笔", en: "tattoo pen" },
    { zh: "金表", en: "gold watch" },
    { zh: "雪茄", en: "cigar" },
    { zh: "盒中手枪", en: "handgun in case" },
    { zh: "威士忌瓶", en: "whiskey bottle" },
    { zh: "名片", en: "business card" },
    { zh: "现金捆", en: "Cash Bundle" },
    { zh: "弹簧刀", en: "Switchblade" },
  ],
  "40_detective": [
    { zh: "放大镜", en: "magnifying glass" },
    { zh: "左轮手枪", en: "revolver" },
    { zh: "案件档案", en: "case file" },
    { zh: "证物袋", en: "evidence bag" },
    { zh: "软呢帽", en: "fedora" },
    { zh: "记事本", en: "notepad" },
    { zh: "手电筒", en: "Flashlight" },
    { zh: "警徽", en: "Police Badge" },
  ],
  "41_military": [
    { zh: "突击步枪", en: "assault rifle" },
    { zh: "军牌", en: "dog tags" },
    { zh: "战斗刀", en: "combat knife" },
    { zh: "军粮包", en: "MRE pack" },
    { zh: "手榴弹", en: "grenade" },
    { zh: "战斗头盔", en: "combat helmet" },
    { zh: "弹匣", en: "Magazine" },
    { zh: "望远镜", en: "Binoculars" },
  ],
  "42_spy": [
    { zh: "消音手枪", en: "silenced pistol" },
    { zh: "公文包", en: "briefcase" },
    { zh: "隐藏摄像机", en: "hidden camera" },
    { zh: "假护照", en: "fake passport" },
    { zh: "窃听器", en: "listening device" },
    { zh: "马天尼杯", en: "martini glass" },
    { zh: "开锁工具包", en: "Lockpick Kit" },
    { zh: "特工手表", en: "Spy Watch" },
  ],
  "43_ancient": [
    { zh: "黄金神像", en: "golden idol" },
    { zh: "石碑", en: "stone tablet" },
    { zh: "黑曜石刀", en: "obsidian blade" },
    { zh: "羽毛头饰", en: "feathered headdress" },
    { zh: "仪式面具", en: "ceremonial mask" },
    { zh: "陶罐", en: "clay pot" },
    { zh: "玉佩", en: "Jade Pendant" },
    { zh: "竹简", en: "Bamboo Scroll" },
  ],
  "44_pirate": [
    { zh: "弯刀", en: "cutlass" },
    { zh: "藏宝图", en: "treasure map" },
    { zh: "单筒望远镜", en: "spyglass" },
    { zh: "罗盘", en: "compass" },
    { zh: "海盗帽", en: "pirate hat" },
    { zh: "朗姆酒瓶", en: "rum bottle" },
    { zh: "金币杜布隆", en: "gold doubloon" },
    { zh: "船锚", en: "Anchor" },
  ],
  "45_industrial": [
    { zh: "煤块", en: "coal lump" },
    { zh: "扳手", en: "wrench" },
    { zh: "怀表", en: "pocket watch" },
    { zh: "工厂汽笛", en: "factory whistle" },
    { zh: "煤灰信件", en: "soot-stained letter" },
    { zh: "铁钥匙", en: "iron key" },
    { zh: "齿轮", en: "Gear" },
    { zh: "煤油灯", en: "Kerosene Lamp" },
  ],
  "46_ww2": [
    { zh: "栓动步枪", en: "bolt-action rifle" },
    { zh: "口粮罐", en: "ration tin" },
    { zh: "野战电台", en: "field radio" },
    { zh: "钢盔", en: "steel helmet" },
    { zh: "战时书信", en: "wartime letter" },
    { zh: "防毒面具", en: "gas mask" },
    { zh: "军用水壶", en: "Military Canteen" },
    { zh: "军用望远镜", en: "Military Binoculars" },
  ],
  "47_coldwar": [
    { zh: "公文包文件", en: "briefcase documents" },
    { zh: "解码戒指", en: "decoder ring" },
    { zh: "转盘电话", en: "rotary phone" },
    { zh: "香烟盒", en: "cigarette pack" },
    { zh: "间谍相机", en: "spy camera" },
    { zh: "胶卷罐", en: "Film Canister" },
    { zh: "红色证件", en: "Red Passport" },
    { zh: "短波电台", en: "Shortwave Radio" },
  ],
  "48_western": [
    { zh: "左轮手枪", en: "revolver" },
    { zh: "牛仔帽", en: "cowboy hat" },
    { zh: "威士忌瓶", en: "whiskey bottle" },
    { zh: "警长徽章", en: "sheriff badge" },
    { zh: "套索", en: "lasso" },
    { zh: "马蹄铁", en: "horseshoe" },
    { zh: "通缉令", en: "wanted poster" },
    { zh: "荒漠骸骨", en: "Desert Skull" },
  ],
  "49_edo": [
    { zh: "武士刀", en: "katana" },
    { zh: "浮世绘扇", en: "ukiyo-e fan" },
    { zh: "清酒杯", en: "sake cup" },
    { zh: "两币钱袋", en: "ryo coin purse" },
    { zh: "武士甲胄", en: "samurai armor" },
    { zh: "烟斗", en: "pipe" },
    { zh: "漆印笼", en: "Lacquer Inro" },
    { zh: "斗笠", en: "Straw Hat" },
  ],
  "50_epichero": [
    { zh: "传说英雄剑", en: "legendary hero sword" },
    { zh: "英雄徽章", en: "hero medallion" },
    { zh: "泰坦号角", en: "titan horn" },
    { zh: "天界盾牌", en: "celestial shield" },
    { zh: "神酒瓶", en: "ambrosia flask" },
    { zh: "月桂冠", en: "Laurel Wreath" },
    { zh: "雷霆护手", en: "Thunder Gauntlet" },
    { zh: "太阳战盔", en: "Sun Helm" },
  ],
  "51_magicreal": [
    { zh: "漂浮蒸汽咖啡杯", en: "coffee cup with floating steam swirl" },
    { zh: "发光书页之书", en: "book with glowing pages" },
    { zh: "微光现代钥匙扣", en: "modern keychain faint glow" },
    { zh: "魔法提灯", en: "Magic Lantern" },
    { zh: "怀表", en: "Pocket Watch" },
    { zh: "星云瓶", en: "Nebula Bottle" },
    { zh: "羽毛笔", en: "Quill Pen" },
    { zh: "罗盘", en: "Compass" },
  ],
  "52_paranormal": [
    { zh: "通灵板指针", en: "ouija planchette" },
    { zh: "电磁场探测器", en: "EMF detector" },
    { zh: "幽灵相机", en: "ghost camera" },
    { zh: "诅咒项链盒", en: "cursed locket" },
    { zh: "盐圈套装", en: "salt circle kit" },
    { zh: "幽灵探测仪", en: "Ghost Detector" },
    { zh: "灵魂灯", en: "Spirit Lantern" },
    { zh: "幽灵瓶", en: "Ghost Bottle" },
  ],
  "53_cartoon": [
    { zh: "巨大卡通炸弹", en: "giant cartoon bomb" },
    { zh: "橡胶鸡", en: "rubber chicken" },
    { zh: "屁垫", en: "whoopee cushion" },
    { zh: "夸张大锤", en: "oversized hammer" },
    { zh: "奶油派", en: "pie in face" },
    { zh: "喷水花", en: "Squirt Flower" },
    { zh: "香蕉皮", en: "Banana Peel" },
    { zh: "喇叭", en: "Horn" },
  ],
  "54_cozy": [
    { zh: "热茶杯", en: "warm tea cup" },
    { zh: "针织围巾", en: "knitted scarf" },
    { zh: "盆栽植物", en: "potted plant" },
    { zh: "翻开的书", en: "open book" },
    { zh: "饼干罐", en: "cookie jar" },
    { zh: "软枕头", en: "soft pillow" },
    { zh: "花纹蜡烛", en: "Floral Candle" },
    { zh: "棉拖鞋", en: "Cozy Slippers" },
  ],
  "55_abstract": [
    { zh: "几何形遗物", en: "geometric shape artifact" },
    { zh: "漂浮水晶", en: "floating crystal" },
    { zh: "画笔", en: "paint brush" },
    { zh: "墨迹圆球", en: "ink blot orb" },
    { zh: "调色盘", en: "Paint Palette" },
    { zh: "彩色画板", en: "Color Board" },
    { zh: "棱镜", en: "Prism" },
    { zh: "颜料药水", en: "Paint Potion" },
  ],
  "56_surreal": [
    { zh: "融化时钟", en: "melting clock" },
    { zh: "漂浮眼球", en: "floating eye" },
    { zh: "不可能楼梯徽记", en: "impossible staircase token" },
    { zh: "会说话的鱼", en: "talking fish" },
    { zh: "反向钥匙", en: "backwards key" },
    { zh: "幻焰蜡烛", en: "Mystic Candle" },
    { zh: "梦月", en: "Dream Moon" },
    { zh: "星云药瓶", en: "Nebula Flask" },
  ],
  "57_religious": [
    { zh: "黄金圣物盒", en: "golden reliquary" },
    { zh: "念珠", en: "prayer beads" },
    { zh: "彩绘玻璃碎片", en: "stained glass shard" },
    { zh: "神圣经卷", en: "sacred scripture" },
    { zh: "天使羽毛", en: "angel feather" },
    { zh: "圣杯", en: "holy chalice" },
    { zh: "圣香炉", en: "Holy Censer" },
    { zh: "圣烛台", en: "Sacred Candlestick" },
  ],
  "58_circushorror": [
    { zh: "染血小丑面具", en: "bloody clown mask" },
    { zh: "诅咒门票", en: "cursed ticket" },
    { zh: "闹鬼八音盒", en: "haunted music box" },
    { zh: "气球", en: "balloon" },
    { zh: "扭曲爆米花桶", en: "twisted popcorn bucket" },
    { zh: "马戏鼓", en: "Circus Drum" },
    { zh: "骷髅手杖", en: "Skull Cane" },
    { zh: "旋转木马头", en: "Carousel Horse Head" },
  ],
  "59_arctic": [
    { zh: "毛皮大衣", en: "fur coat" },
    { zh: "冰镐", en: "ice pick" },
    { zh: "冻肉", en: "frozen meat" },
    { zh: "点火器", en: "fire starter" },
    { zh: "雪地护目镜", en: "snow goggles" },
    { zh: "应急信号棒", en: "emergency flare" },
    { zh: "雪地手套", en: "Snow Gloves" },
    { zh: "保温瓶", en: "Thermos" },
  ],
  "60_deepsea": [
    { zh: "潜水头盔", en: "diving helmet" },
    { zh: "加压瓶", en: "pressurized flask" },
    { zh: "生物荧光灯笼", en: "bioluminescent lantern" },
    { zh: "珊瑚遗物", en: "coral artifact" },
    { zh: "鱼叉", en: "harpoon" },
    { zh: "航海罗盘", en: "Nautical Compass" },
    { zh: "潜水仪表", en: "Diving Gauge" },
    { zh: "深海罐", en: "Deep Sea Canister" },
  ],
  "61_spaceexplore": [
    { zh: "反光宇航头盔", en: "helmet with reflection" },
    { zh: "氧气罐", en: "oxygen tank" },
    { zh: "星图", en: "star map" },
    { zh: "外星岩石样本", en: "alien rock sample" },
    { zh: "航行记录仪", en: "log recorder" },
    { zh: "雷达表", en: "Radar Watch" },
    { zh: "能量电池", en: "Energy Cell" },
    { zh: "太空胶囊", en: "Space Capsule" },
  ],
  "62_indian": [
    { zh: "莲花", en: "lotus flower" },
    { zh: "三叉戟", en: "trishul trident" },
    { zh: "圣海螺", en: "sacred conch" },
    { zh: "宾迪宝石", en: "bindi gem" },
    { zh: "纱丽布料", en: "sari cloth" },
    { zh: "祈祷铃", en: "prayer bell" },
    { zh: "油灯", en: "Oil Lamp" },
    { zh: "孔雀羽饰", en: "Peacock Feather" },
  ],
  "63_arabian": [
    { zh: "神灯", en: "magic lamp" },
    { zh: "飞毯碎片", en: "flying carpet piece" },
    { zh: "弯月刀", en: "scimitar" },
    { zh: "精灵宝石", en: "genie jewel" },
    { zh: "香料袋", en: "spice bag" },
    { zh: "黄铜茶壶", en: "brass teapot" },
    { zh: "金钥匙", en: "Golden Key" },
    { zh: "月牙坠饰", en: "Crescent Pendant" },
  ],
  "64_african": [
    { zh: "部落面具", en: "tribal mask" },
    { zh: "木矛", en: "wooden spear" },
    { zh: "串珠项链", en: "beaded necklace" },
    { zh: "鼓", en: "drum" },
    { zh: "祖灵图腾", en: "ancestor totem" },
    { zh: "猴面包树种子", en: "baobab seed" },
    { zh: "图腾权杖", en: "Totem Staff" },
    { zh: "太阳护符", en: "Sun Amulet" },
  ],
  "65_southamerican": [
    { zh: "印加黄金面具", en: "Incan gold mask" },
    { zh: "羽毛头饰", en: "feathered headdress" },
    { zh: "黑曜石镜", en: "obsidian mirror" },
    { zh: "结绳记事", en: "quipu knots" },
    { zh: "古柯叶", en: "coca leaves" },
    { zh: "翡翠神像", en: "Jade Idol" },
    { zh: "黄金弯刀", en: "Golden Sickle" },
    { zh: "太阳圆盘", en: "Sun Disk" },
  ],
  "66_slavic": [
    { zh: "桦树皮护符", en: "birch bark charm" },
    { zh: "木制神像", en: "wooden idol" },
    { zh: "诅咒娃娃", en: "cursed doll" },
    { zh: "铁骷髅钥匙", en: "iron skull key" },
    { zh: "刺绣布", en: "embroidered cloth" },
    { zh: "符文号角", en: "Rune Horn" },
    { zh: "浆果护符", en: "Berry Amulet" },
    { zh: "太阳护符", en: "Sun Amulet" },
  ],
  "67_mongol": [
    { zh: "弯马刀", en: "curved saber" },
    { zh: "马鞭", en: "horse whip" },
    { zh: "毡房护符", en: "yurt charm" },
    { zh: "萨满鼓", en: "shaman drum" },
    { zh: "马奶酒壶", en: "airag flask" },
    { zh: "复合弓", en: "composite bow" },
    { zh: "蒙古靴", en: "Mongol Boots" },
    { zh: "皮护臂", en: "Leather Bracer" },
  ],
  "68_sea": [
    { zh: "金色那伽护符", en: "gold naga amulet" },
    { zh: "贝叶经卷", en: "palm leaf scroll" },
    { zh: "克里斯短剑", en: "kris dagger" },
    { zh: "塔香", en: "incense cone" },
    { zh: "皮影偶", en: "wayang puppet" },
    { zh: "祭钟", en: "Ceremonial Bell" },
    { zh: "恶魔面具", en: "Demon Mask" },
    { zh: "宝石供碗", en: "Gem Offering Bowl" },
  ],
  "69_dystopia": [
    { zh: "监控摄像头", en: "surveillance camera" },
    { zh: "公民身份证", en: "citizen ID card" },
    { zh: "配给票", en: "ration ticket" },
    { zh: "禁书", en: "banned book" },
    { zh: "政权徽章", en: "regime pin" },
    { zh: "扩音器", en: "Megaphone" },
    { zh: "道闸杆", en: "Barrier Gate" },
    { zh: "信号干扰器", en: "Signal Jammer" },
  ],
  "70_multiverse": [
    { zh: "现实碎片", en: "reality shard" },
    { zh: "传送门钥匙", en: "portal key" },
    { zh: "时间线碎片", en: "timeline fragment" },
    { zh: "维度罗盘", en: "dimensional compass" },
    { zh: "平行硬币", en: "parallel coin" },
    { zh: "维度晶片", en: "Dimensional Chip" },
    { zh: "虚空方块", en: "Void Cube" },
    { zh: "旋涡装置", en: "Vortex Device" },
  ],
  "71_timeloop": [
    { zh: "破损怀表", en: "broken pocket watch" },
    { zh: "循环沙漏", en: "looping hourglass" },
    { zh: "记忆笔记本", en: "memory notebook" },
    { zh: "悖论硬币", en: "paradox coin" },
    { zh: "罗盘", en: "Compass" },
    { zh: "倒带钥匙", en: "Rewind Key" },
    { zh: "时光灯笼", en: "Time Lantern" },
    { zh: "时间瓶", en: "Time Bottle" },
  ],
  "72_monster": [
    { zh: "捕获球", en: "capture ball" },
    { zh: "怪物糖果", en: "monster candy" },
    { zh: "进化石", en: "evolution stone" },
    { zh: "训练师徽章", en: "trainer badge" },
    { zh: "生物图鉴", en: "creature journal" },
    { zh: "红药水", en: "Red Potion" },
    { zh: "彩虹羽毛", en: "Rainbow Feather" },
    { zh: "怪物蛋", en: "Monster Egg" },
  ],
  "73_cooking": [
    { zh: "厨师刀", en: "chef knife" },
    { zh: "煎锅", en: "frying pan" },
    { zh: "新鲜蔬菜", en: "fresh vegetable" },
    { zh: "食谱书", en: "recipe book" },
    { zh: "香料罐", en: "spice jar" },
    { zh: "金色面包", en: "golden bread" },
    { zh: "汤锅", en: "Soup Pot" },
    { zh: "砧板", en: "Cutting Board" },
  ],
  "74_sports": [
    { zh: "奖杯", en: "trophy" },
    { zh: "足球", en: "soccer ball" },
    { zh: "跑鞋", en: "running shoes" },
    { zh: "秒表", en: "stopwatch" },
    { zh: "队服", en: "team jersey" },
    { zh: "哨子", en: "whistle" },
    { zh: "篮球", en: "Basketball" },
    { zh: "球棒", en: "Baseball Bat" },
  ],
  "75_music": [
    { zh: "电吉他", en: "electric guitar" },
    { zh: "黑胶唱片", en: "vinyl record" },
    { zh: "音符水晶", en: "music note crystal" },
    { zh: "耳机", en: "headphones" },
    { zh: "鼓槌", en: "drum stick" },
    { zh: "麦克风", en: "microphone" },
    { zh: "收音机", en: "Boombox" },
    { zh: "合成器", en: "Synthesizer" },
  ],
  "76_otome": [
    { zh: "情书", en: "love letter" },
    { zh: "玫瑰花束", en: "rose bouquet" },
    { zh: "爱心吊坠", en: "heart pendant" },
    { zh: "巧克力盒", en: "chocolate box" },
    { zh: "相册", en: "photo album" },
    { zh: "日记本", en: "diary" },
    { zh: "戒指盒", en: "Ring Box" },
    { zh: "香水瓶", en: "Perfume Bottle" },
  ],
}

export function getHomepageExampleItemSubject(example: HomepageExample, index: number, language: 'zh-CN' | 'en') {
  const subject = homepageExampleItemSubjects[example.id]?.[index]
  const fallbackSlot = String(index + 1).padStart(2, '0')
  if (language === 'en') return subject?.en || `${deriveEnglishTheme(example)} icon ${fallbackSlot}`
  return subject?.zh || `${example.theme}图标 ${fallbackSlot}`
}

export function getHomepageExampleItemSubjectPrompt(example: HomepageExample, index: number, language: 'zh-CN' | 'en') {
  const subject = getHomepageExampleItemSubject(example, index, language)
  if (language === 'en') {
    return `${subject}, ${deriveEnglishTheme(example)} themed single prop, emphasize its recognizable shape, material, and game-inventory readability`
  }
  return `${subject}，${example.theme}题材单个道具，突出可识别造型、材质特征和背包图标可读性`
}

export function getHomepageExampleItemSubjectList(example: HomepageExample, language: 'zh-CN' | 'en') {
  return Array.from({ length: itemSlotCount }, (_, index) => getHomepageExampleItemSubjectPrompt(example, index, language))
}

export function buildHomepageExampleItemPrompt(example: HomepageExample, index: number, variant: HomepageExampleItemVariant, language: 'zh-CN' | 'en') {
  const subjectPrompt = getHomepageExampleItemSubjectPrompt(example, index, language)
  if (language === 'en') {
    const sizeLead = variant === 'original64' ? '64×64 pixel game item icon' : '32×32 outline pixel game item icon'
    return `${sizeLead}, retro 8-bit pixel art style, single prop, theme: ${deriveEnglishTheme(example)}, subject: ${subjectPrompt}, clean solid background, clear silhouette, sharp pixel blocks, crisp outline, limited palette, no anti-aliasing, square canvas, transparent PNG game asset.`
  }
  const sizeLead = variant === 'original64' ? '64×64 像素游戏物品图标' : '32×32 outline 像素游戏物品图标'
  return `${sizeLead}，复古 8 位像素风格，单个道具，题材：${example.theme}，主体：${subjectPrompt}，纯色干净背景，轮廓清晰，色块分明，线条锐利，有限调色板，无抗锯齿，正方形画幅，透明 PNG 游戏素材。`
}

export function buildHomepageExampleItemSetPrompt(example: HomepageExample, language: 'zh-CN' | 'en') {
  const subjects = getHomepageExampleItemSubjectList(example, language)
  if (language === 'en') {
    return `Pixel art ${deriveEnglishTheme(example)} item icon set, 4×2 sheet with 8 independent prop slots: ${subjects.join(', ')}; includes original 64×64 transparent resources plus new 32×32 outline icon exports, centered composition, crisp pixels, limited palette, no anti-aliasing, readable as inventory icons and loot assets.`
  }
  return `像素风「${example.theme}」物品图标组，4×2 共 8 个独立道具格：${subjects.join('、')}；同时展示原 64×64 透明资源和新 32×32 outline 图标，居中构图、硬边像素、有限调色板、无抗锯齿，适合作为背包图标或掉落物素材。`
}

export function buildHomepageExampleUiPrompt(example: HomepageExample, language: 'zh-CN' | 'en') {
  if (language === 'en') return example.uiPrompt
  return `像素风「${example.theme}」16:9 UI 展示图，围绕「${example.category}」题材设计主题面板、边框、按钮、图标、状态区和游戏界面示例；16-bit RPG / 独立游戏可用风格，干净像素边框、可读图标、无抗锯齿，1920×1080 展示布局。`
}

function deriveEnglishTheme(example: HomepageExample) {
  const match = example.itemPrompt.match(/^pixel art ([^,]+?) items/i)
  return (match?.[1] ?? example.id.replace(/^\d+_/, '').replace(/[_-]+/g, ' ')).trim()
}

