import { useState } from 'react'
import { Clipboard, Eye } from 'lucide-react'
import { api } from '../api'
import { useI18n } from '../i18n'
import type { JobCreateRequest, PromptPreviewResponse } from '../types'
import { Alert } from './ui/alert'
import { Badge } from './ui/badge'
import { Button } from './ui/button'
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from './ui/dialog'

type Props = {
  token: string
  buildPayload: () => JobCreateRequest | null
  disabled?: boolean
  label?: string
}

export function PromptPreviewDialog({ token, buildPayload, disabled = false, label }: Props) {
  const { text } = useI18n()
  const [open, setOpen] = useState(false)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const [preview, setPreview] = useState<PromptPreviewResponse | null>(null)
  const [copied, setCopied] = useState(false)

  async function loadPreview() {
    const payload = buildPayload()
    if (!payload) return
    setOpen(true)
    setLoading(true)
    setError('')
    setPreview(null)
    setCopied(false)
    try {
      const result = await api.promptPreview(token, payload)
      setPreview(result)
    } catch (err) {
      setError(err instanceof Error ? err.message : text('预览失败', 'Preview failed'))
    } finally {
      setLoading(false)
    }
  }

  async function copyPrompt() {
    if (!preview?.positive_prompt) return
    await navigator.clipboard.writeText(preview.positive_prompt)
    setCopied(true)
    window.setTimeout(() => setCopied(false), 1600)
  }

  return (
    <>
      <Button type="button" variant="outline" disabled={disabled || loading} onClick={() => void loadPreview()}>
        <Eye />{label ?? text('预览 Prompt', 'Preview prompt')}
      </Button>
      <Dialog open={open} onOpenChange={setOpen}>
        <DialogContent className="w-[min(92vw,820px)]">
          <DialogHeader>
            <DialogTitle>{text('Prompt 预览', 'Prompt preview')}</DialogTitle>
            <DialogDescription>{text('由服务端按真实模板生成；预览不会创建任务、不会扣点。', 'Generated by the server using the real templates; this does not create a job or spend credits.')}</DialogDescription>
          </DialogHeader>

          {loading && <Alert variant="info">{text('正在生成预览…', 'Building preview…')}</Alert>}
          {error && <Alert variant="destructive">{error}</Alert>}

          {preview && (
            <div className="grid gap-4">
              <div className="flex flex-wrap items-center gap-2">
                <Badge variant="secondary">{preview.mode}</Badge>
                {(preview.applied_style_profile?.length ?? 0) > 0 && <Badge variant="info">{text(`已应用 ${preview.applied_style_profile.length} 条风格规则`, `${preview.applied_style_profile.length} style rules applied`)}</Badge>}
              </div>

              {(preview.applied_style_profile?.length ?? 0) > 0 && (
                <div className="grid gap-2 rounded-lg border border-border bg-muted/35 p-3 text-sm dark:border-[hsl(var(--pix-dark-hairline))] dark:bg-[hsl(var(--pix-dark-band-soft))]">
                  <div className="text-xs font-semibold text-muted-foreground">{text('已应用风格档案', 'Applied style profile')}</div>
                  <ul className="grid gap-1">
                    {preview.applied_style_profile.map((item) => <li key={item}>• {item}</li>)}
                  </ul>
                </div>
              )}

              {(preview.warnings ?? []).map((warning) => <Alert key={warning} variant="warning">{warning}</Alert>)}

              <div className="grid gap-2">
                <div className="text-xs font-semibold text-muted-foreground">{text('正向 Prompt', 'Positive prompt')}</div>
                <pre className="max-h-[50dvh] overflow-auto whitespace-pre-wrap rounded-lg border border-border bg-background p-4 text-xs leading-6 dark:border-[hsl(var(--pix-dark-hairline))] dark:bg-[hsl(var(--pix-dark-card))]">{preview.positive_prompt || text('当前模式没有可预览的 Prompt。', 'This mode has no prompt to preview.')}</pre>
              </div>
            </div>
          )}

          <DialogFooter>
            <Button type="button" variant="outline" onClick={() => setOpen(false)}>{text('关闭', 'Close')}</Button>
            <Button type="button" disabled={!preview?.positive_prompt} onClick={() => void copyPrompt()}><Clipboard />{copied ? text('已复制', 'Copied') : text('复制 Prompt', 'Copy prompt')}</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </>
  )
}
